name: Simple Secrets Demo

on:
  push:
    branches:
      - main

jobs:

  staging:
    runs-on: ubuntu-latest
    environment: staging

    env:
      ENV_NAME: staging

    steps:
      - uses: actions/checkout@v4

      - name: Use Staging Secret
        run: echo "Staging Key = ${{ secrets.API_KEY }}"

  production:
    runs-on: ubuntu-latest
    needs: staging
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Use Production Secret
